import type { IconType } from "react-icons";
import {
  PiDog,
  PiFlag,
  PiHandWaving,
  PiHeart,
  PiLightbulb,
  PiPizza,
  PiSmiley,
} from "react-icons/pi";

export type Emoji = {
  char: string;
  name: string;
  keywords?: string[];
  skin?: number;
};

export type EmojiCategory = {
  id: string;
  label: string;
  icon: IconType;
  items: Emoji[];
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: PiSmiley,
    items: [
      { char: "😀", name: "grinning face", keywords: ["smile", "happy"] },
      { char: "😃", name: "grinning face with big eyes", keywords: ["smile", "open"] },
      { char: "😄", name: "grinning face with smiling eyes", keywords: ["smile"] },
      { char: "😁", name: "beaming face with smiling eyes", keywords: ["smile", "grin"] },
      { char: "😆", name: "grinning squinting face", keywords: ["laugh"] },
      { char: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "lol"] },
      { char: "😂", name: "face with tears of joy", keywords: ["lol", "joy"] },
      { char: "🙂", name: "slightly smiling face", keywords: ["smile"] },
      { char: "😊", name: "smiling face with smiling eyes", keywords: ["blush"] },
      { char: "😉", name: "winking face", keywords: ["wink"] },
      { char: "😍", name: "smiling face with heart-eyes", keywords: ["love"] },
      { char: "😘", name: "face blowing a kiss", keywords: ["kiss", "love"] },
      { char: "😗", name: "kissing face", keywords: ["kiss"] },
      { char: "😙", name: "kissing face with smiling eyes", keywords: ["kiss", "smile"] },
      { char: "😚", name: "kissing face with closed eyes", keywords: ["kiss"] },
      { char: "😋", name: "face savoring food", keywords: ["yum", "delicious"] },
      { char: "😛", name: "face with tongue", keywords: ["tongue", "funny"] },
      { char: "😜", name: "winking face with tongue", keywords: ["prank"] },
      { char: "🤪", name: "zany face", keywords: ["crazy", "goofy"] },
      { char: "😝", name: "squinting face with tongue", keywords: ["prank"] },
      { char: "🤗", name: "smiling face with open hands", keywords: ["hug"] },
      { char: "🤔", name: "thinking face", keywords: ["think", "hmm"] },
      { char: "🤨", name: "face with raised eyebrow", keywords: ["suspicious"] },
      { char: "🤔", name: "face with diagonal mouth", keywords: ["meh"] },
      { char: "😐", name: "neutral face", keywords: ["neutral"] },
      { char: "😑", name: "expressionless face", keywords: ["blank"] },
      { char: "😶", name: "face without mouth", keywords: ["silent"] },
      { char: "😏", name: "smirking face", keywords: ["smirk"] },
      { char: "😒", name: "unamused face", keywords: ["meh"] },
      { char: "🙄", name: "face with rolling eyes", keywords: ["eyeroll"] },
      { char: "😬", name: "grimacing face", keywords: ["awkward"] },
      { char: "🤥", name: "lying face", keywords: ["lie", "pinocchio"] },
      { char: "😴", name: "sleeping face", keywords: ["sleep", "zzz"] },
      { char: "😪", name: "sleepy face", keywords: ["tired"] },
      { char: "😤", name: "face exhaling", keywords: ["relief"] },
      { char: "😮", name: "face with open mouth", keywords: ["surprised"] },
      { char: "😯", name: "hushed face", keywords: ["quiet"] },
      { char: "😲", name: "astonished face", keywords: ["shock"] },
      { char: "😳", name: "flushed face", keywords: ["blush", "embarrassed"] },
      { char: "🥺", name: "pleading face", keywords: ["please", "cute"] },
      { char: "😭", name: "loudly crying face", keywords: ["cry"] },
      { char: "😤", name: "face with steam from nose", keywords: ["angry", "proud"] },
      { char: "😡", name: "pouting face", keywords: ["angry", "mad"] },
      { char: "😠", name: "angry face", keywords: ["mad"] },
      { char: "🤯", name: "exploding head", keywords: ["mind blown"] },
      { char: "😎", name: "smiling face with sunglasses", keywords: ["cool"] },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    icon: PiHandWaving,
    items: [
      { char: "👍", name: "thumbs up", keywords: ["like", "approve"] },
      { char: "👎", name: "thumbs down", keywords: ["dislike"] },
      { char: "👏", name: "clapping hands", keywords: ["applause", "bravo"] },
      { char: "🙏", name: "folded hands", keywords: ["please", "thanks"] },
      { char: "👌", name: "OK hand", keywords: ["ok", "perfect"] },
      { char: "🤝", name: "handshake", keywords: ["deal"] },
      { char: "👋", name: "waving hand", keywords: ["hello", "hi"] },
      { char: "✌️", name: "victory hand", keywords: ["peace"] },
      { char: "🤞", name: "crossed fingers", keywords: ["luck"] },
      { char: "🤟", name: "i love you hand sign", keywords: ["ily", "love"] },
      { char: "☝️", name: "index pointing up", keywords: ["up"] },
      { char: "👇", name: "backhand index pointing down", keywords: ["down"] },
      { char: "👈", name: "backhand index pointing left", keywords: ["left"] },
      { char: "👉", name: "backhand index pointing right", keywords: ["right"] },
      { char: "✋", name: "raised hand", keywords: ["stop", "hi"] },
      { char: "🖐️", name: "hand with fingers splayed", keywords: ["hi"] },
      { char: "🤏", name: "pinching hand", keywords: ["small"] },
      { char: "👊", name: "oncoming fist", keywords: ["fist bump"] },
    ],
  },
  {
    id: "animals",
    label: "Animals",
    icon: PiDog,
    items: [
      { char: "🐶", name: "dog face", keywords: ["dog", "pet"] },
      { char: "🐱", name: "cat face", keywords: ["cat"] },
      { char: "🐭", name: "mouse face", keywords: ["mouse"] },
      { char: "🐹", name: "hamster", keywords: ["hamster"] },
      { char: "🐰", name: "rabbit face", keywords: ["bunny"] },
      { char: "🦊", name: "fox", keywords: ["fox"] },
      { char: "🐻", name: "bear", keywords: ["bear"] },
      { char: "🐼", name: "panda", keywords: ["bear"] },
      { char: "🐨", name: "koala", keywords: ["bear"] },
      { char: "🐯", name: "tiger face", keywords: ["tiger"] },
      { char: "🦁", name: "lion", keywords: ["cat", "king"] },
      { char: "🐮", name: "cow face", keywords: ["cow"] },
      { char: "🐷", name: "pig face", keywords: ["pig"] },
      { char: "🐸", name: "frog", keywords: ["frog"] },
      { char: "🐵", name: "monkey face", keywords: ["monkey"] },
      { char: "🐔", name: "chicken", keywords: ["chicken"] },
      { char: "🐧", name: "penguin", keywords: ["bird", "cold"] },
      { char: "🐦", name: "bird", keywords: ["bird"] },
      { char: "🐤", name: "baby chick", keywords: ["chick"] },
      { char: "🦆", name: "duck", keywords: ["duck"] },
      { char: "🦅", name: "eagle", keywords: ["bird"] },
      { char: "🦉", name: "owl", keywords: ["bird", "night"] },
      { char: "🐢", name: "turtle", keywords: ["turtle"] },
      { char: "🐍", name: "snake", keywords: ["snake"] },
      { char: "🦖", name: "t-rex", keywords: ["dinosaur"] },
      { char: "🦕", name: "sauropod", keywords: ["dinosaur"] },
      { char: "🐙", name: "octopus", keywords: ["octopus"] },
      { char: "🦑", name: "squid", keywords: ["squid"] },
      { char: "🐠", name: "tropical fish", keywords: ["fish"] },
      { char: "🐬", name: "dolphin", keywords: ["dolphin"] },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: PiPizza,
    items: [
      { char: "🍎", name: "red apple", keywords: ["apple", "fruit"] },
      { char: "🍏", name: "green apple", keywords: ["apple", "fruit"] },
      { char: "🍇", name: "grapes", keywords: ["fruit"] },
      { char: "🍉", name: "watermelon", keywords: ["fruit", "summer"] },
      { char: "🍌", name: "banana", keywords: ["fruit"] },
      { char: "🍍", name: "pineapple", keywords: ["fruit"] },
      { char: "🍓", name: "strawberry", keywords: ["fruit"] },
      { char: "🍑", name: "peach", keywords: ["fruit"] },
      { char: "🥭", name: "mango", keywords: ["fruit"] },
      { char: "🍒", name: "cherries", keywords: ["fruit"] },
      { char: "🥝", name: "kiwi fruit", keywords: ["fruit"] },
      { char: "🍅", name: "tomato", keywords: ["vegetable", "fruit"] },
      { char: "🥑", name: "avocado", keywords: ["avocado"] },
      { char: "🍔", name: "hamburger", keywords: ["burger", "fast food"] },
      { char: "🍟", name: "french fries", keywords: ["fries"] },
      { char: "🌭", name: "hot dog", keywords: ["hotdog"] },
      { char: "🍕", name: "pizza", keywords: ["slice", "cheese"] },
      { char: "🌮", name: "taco", keywords: ["mexican"] },
      { char: "🌯", name: "burrito", keywords: ["mexican"] },
      { char: "🍜", name: "steaming bowl", keywords: ["noodles", "ramen"] },
      { char: "🍝", name: "spaghetti", keywords: ["pasta"] },
      { char: "🍣", name: "sushi", keywords: ["japanese"] },
      { char: "🍱", name: "bento box", keywords: ["japanese"] },
      { char: "🍰", name: "cake", keywords: ["dessert"] },
      { char: "🧁", name: "cupcake", keywords: ["dessert"] },
      { char: "🍪", name: "cookie", keywords: ["dessert"] },
      { char: "🍩", name: "doughnut", keywords: ["dessert"] },
      { char: "🍫", name: "chocolate bar", keywords: ["dessert"] },
      { char: "🍨", name: "ice cream", keywords: ["dessert"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: PiLightbulb,
    items: [
      { char: "💡", name: "light bulb", keywords: ["idea", "smart"] },
      { char: "🔑", name: "key", keywords: ["key"] },
      { char: "🔒", name: "locked", keywords: ["lock"] },
      { char: "🔓", name: "unlocked", keywords: ["unlock"] },
      { char: "🗝️", name: "old key", keywords: ["key"] },
      { char: "📱", name: "mobile phone", keywords: ["phone"] },
      { char: "💻", name: "laptop", keywords: ["computer"] },
      { char: "🖥️", name: "desktop computer", keywords: ["computer"] },
      { char: "⌨️", name: "keyboard", keywords: ["keyboard"] },
      { char: "🖱️", name: "computer mouse", keywords: ["mouse"] },
      { char: "🖨️", name: "printer", keywords: ["printer"] },
      { char: "🕹️", name: "joystick", keywords: ["game"] },
      { char: "🎧", name: "headphone", keywords: ["music"] },
      { char: "🎤", name: "microphone", keywords: ["mic"] },
      { char: "🎬", name: "clapper board", keywords: ["movie"] },
      { char: "📷", name: "camera", keywords: ["photo"] },
      { char: "📸", name: "camera with flash", keywords: ["photo"] },
      { char: "⏰", name: "alarm clock", keywords: ["clock"] },
      { char: "⏱️", name: "stopwatch", keywords: ["timer"] },
      { char: "📦", name: "package", keywords: ["box"] },
      { char: "📚", name: "books", keywords: ["study"] },
      { char: "📝", name: "memo", keywords: ["note", "write"] },
      { char: "✏️", name: "pencil", keywords: ["write"] },
      { char: "🖊️", name: "pen", keywords: ["write"] },
      { char: "📎", name: "paperclip", keywords: ["clip"] },
      { char: "🧷", name: "safety pin", keywords: ["pin"] },
      { char: "🧯", name: "fire extinguisher", keywords: ["safety"] },
      { char: "🧲", name: "magnet", keywords: ["magnet"] },
      { char: "🧪", name: "test tube", keywords: ["science"] },
      { char: "⚙️", name: "gear", keywords: ["settings"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: PiHeart,
    items: [
      { char: "❤️", name: "red heart", keywords: ["love", "heart"] },
      { char: "🧡", name: "orange heart", keywords: ["love", "heart"] },
      { char: "💛", name: "yellow heart", keywords: ["love", "heart"] },
      { char: "💚", name: "green heart", keywords: ["love", "heart"] },
      { char: "💙", name: "blue heart", keywords: ["love", "heart"] },
      { char: "💜", name: "purple heart", keywords: ["love", "heart"] },
      { char: "🖤", name: "black heart", keywords: ["love", "heart"] },
      { char: "🤍", name: "white heart", keywords: ["love", "heart"] },
      { char: "✨", name: "sparkles", keywords: ["sparkle", "shiny"] },
      { char: "💫", name: "dizzy", keywords: ["sparkle"] },
      { char: "⭐", name: "star", keywords: ["favorite"] },
      { char: "🌟", name: "glowing star", keywords: ["favorite"] },
      { char: "🔥", name: "fire", keywords: ["lit", "hot"] },
      { char: "⚡", name: "high voltage", keywords: ["zap"] },
      { char: "💥", name: "collision", keywords: ["boom"] },
      { char: "💯", name: "hundred points", keywords: ["100", "score"] },
      { char: "✅", name: "check mark button", keywords: ["done", "check"] },
      { char: "❌", name: "cross mark", keywords: ["x", "close"] },
      { char: "❗", name: "exclamation mark", keywords: ["alert"] },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: PiFlag,
    items: [
      { char: "🏳️", name: "white flag", keywords: ["flag"] },
      { char: "🏴", name: "black flag", keywords: ["flag"] },
      { char: "🏁", name: "chequered flag", keywords: ["race"] },
      { char: "🚩", name: "triangular flag", keywords: ["red flag"] },
      { char: "🇺🇸", name: "flag: United States", keywords: ["usa", "america"] },
      { char: "🇬🇧", name: "flag: United Kingdom", keywords: ["uk", "britain"] },
      { char: "🇨🇦", name: "flag: Canada", keywords: ["canada"] },
      { char: "🇦🇺", name: "flag: Australia", keywords: ["australia"] },
      { char: "🇩🇪", name: "flag: Germany", keywords: ["germany"] },
      { char: "🇫🇷", name: "flag: France", keywords: ["france"] },
      { char: "🇪🇸", name: "flag: Spain", keywords: ["spain"] },
      { char: "🇯🇵", name: "flag: Japan", keywords: ["japan"] },
      { char: "🇰🇷", name: "flag: South Korea", keywords: ["korea"] },
      { char: "🇮🇳", name: "flag: India", keywords: ["india"] },
      { char: "🇧🇷", name: "flag: Brazil", keywords: ["brazil"] },
      { char: "🇲🇽", name: "flag: Mexico", keywords: ["mexico"] },
    ],
  },
];

export const ALL_EMOJIS: Emoji[] = EMOJI_CATEGORIES.flatMap((c) => c.items);
